version: '3.8'

services:
  tugasku:
    build: .
    container_name: tugasku_app
    restart: always
    ports:
      - "7025:8501"  # Akses Web Streamlit
      - "8000:8000"  # Akses API GET
    volumes:
      # Sinkronisasi database agar tidak hilang saat container restart
      - ./database_jadwal.json:/app/database_jadwal.json
    environment:
      - TZ=Asia/Jakarta